"""empty message

Revision ID: 1b27f7bd7edb
Revises: c9da92f14083
Create Date: 2020-06-29 13:53:05.681200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b27f7bd7edb'
down_revision = 'c9da92f14083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_hash', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password_hash')
    # ### end Alembic commands ###
