"""empty message

Revision ID: 56244d5ea522
Revises: baa447c03995
Create Date: 2020-07-03 15:29:39.914798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56244d5ea522'
down_revision = 'baa447c03995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yogaclass', 'time')
    # ### end Alembic commands ###
