"""empty message

Revision ID: 5b4080b292fc
Revises: 1b27f7bd7edb
Create Date: 2020-07-03 15:13:26.410553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b4080b292fc'
down_revision = '1b27f7bd7edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_teacher_email'), 'teacher', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_email'), table_name='teacher')
    # ### end Alembic commands ###
