"""empty message

Revision ID: 79c9ff71757a
Revises: 7f00d365bf8f
Create Date: 2020-07-25 18:29:41.757727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79c9ff71757a'
down_revision = '7f00d365bf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('yogaclass', 'Price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('Price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('yogaclass', 'price')
    # ### end Alembic commands ###
