"""empty message

Revision ID: 7d9f057d96d6
Revises: 2828be8e2154
Create Date: 2020-06-15 14:18:41.444576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d9f057d96d6'
down_revision = '2828be8e2154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('username', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'username')
    # ### end Alembic commands ###
