"""empty message

Revision ID: 7f00d365bf8f
Revises: 56244d5ea522
Create Date: 2020-07-17 11:00:58.618852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f00d365bf8f'
down_revision = '56244d5ea522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.alter_column('yogaclass', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('yogaclass', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'yogaclass', 'teacher', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yogaclass', type_='foreignkey')
    op.alter_column('yogaclass', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('yogaclass', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('yogaclass', 'teacher_id')
    # ### end Alembic commands ###
