"""empty message

Revision ID: 85c97eb29f0c
Revises: b59dd82ac180
Create Date: 2020-06-15 16:50:55.115232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c97eb29f0c'
down_revision = 'b59dd82ac180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'teacher', sa.Column('default_timezone', sa.String(length=40), nullable=True))
    op.drop_column(u'teacher', 'timezone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'teacher', sa.Column('timezone', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column(u'teacher', 'default_timezone')
    op.drop_table('student')
    # ### end Alembic commands ###
