"""empty message

Revision ID: be9145bbe602
Revises: ee71b45d7ce4
Create Date: 2020-06-26 20:32:23.331682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9145bbe602'
down_revision = 'ee71b45d7ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
