"""empty message

Revision ID: c198dbe3aca7
Revises: be9145bbe602
Create Date: 2020-06-26 20:39:58.220230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c198dbe3aca7'
down_revision = 'be9145bbe602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password_hash', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'password_hash')
    # ### end Alembic commands ###
