"""empty message

Revision ID: c8795596b887
Revises: 7d9f057d96d6
Create Date: 2020-06-15 14:22:16.038360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8795596b887'
down_revision = '7d9f057d96d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'teacher', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'teacher', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_table('student')
    # ### end Alembic commands ###
