"""empty message

Revision ID: c9da92f14083
Revises: c198dbe3aca7
Create Date: 2020-06-29 13:49:41.340929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9da92f14083'
down_revision = 'c198dbe3aca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_hash', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
