"""empty message

Revision ID: eae267821676
Revises: d172faaefdd1
Create Date: 2020-08-05 15:59:33.899575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae267821676'
down_revision = 'd172faaefdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('yogaclass', sa.Column('time', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yogaclass', 'time')
    op.drop_column('yogaclass', 'date')
    # ### end Alembic commands ###
