"""empty message

Revision ID: ee71b45d7ce4
Revises: c39cb54efd3f
Create Date: 2020-06-18 14:24:49.584361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee71b45d7ce4'
down_revision = 'c39cb54efd3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.add_column('yogaclass', sa.Column('review_id', sa.Integer(), nullable=False))
    op.add_column('yogaclass', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'yogaclass', 'student', ['student_id'], ['id'])
    op.create_foreign_key(None, 'yogaclass', 'review', ['review_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'yogaclass', type_='foreignkey')
    op.drop_constraint(None, 'yogaclass', type_='foreignkey')
    op.drop_column('yogaclass', 'student_id')
    op.drop_column('yogaclass', 'review_id')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    # ### end Alembic commands ###
