"""empty message

Revision ID: fd389c17eb9d
Revises: 2d3a9a71cd54
Create Date: 2020-08-05 15:41:23.489524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd389c17eb9d'
down_revision = '2d3a9a71cd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yogaclass', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yogaclass', 'duration')
    # ### end Alembic commands ###
